// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::{Object,Property,Serializable};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    #[doc(alias = "IBusPropList")]
    pub struct PropList(Object<ffi::IBusPropList, ffi::IBusPropListClass>) @extends Serializable, Object;

    match fn {
        type_ => || ffi::ibus_prop_list_get_type(),
    }
}

impl PropList {
        pub const NONE: Option<&'static PropList> = None;
    

    #[doc(alias = "ibus_prop_list_new")]
    pub fn new() -> PropList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::ibus_prop_list_new())
        }
    }
}

impl Default for PropList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::PropList>> Sealed for T {}
}

pub trait PropListExt: IsA<PropList> + sealed::Sealed + 'static {
    #[doc(alias = "ibus_prop_list_append")]
    fn append(&self, prop: &impl IsA<Property>) {
        unsafe {
            ffi::ibus_prop_list_append(self.as_ref().to_glib_none().0, prop.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "ibus_prop_list_get")]
    fn get(&self, index: u32) -> Option<Property> {
        unsafe {
            from_glib_none(ffi::ibus_prop_list_get(self.as_ref().to_glib_none().0, index))
        }
    }

    #[doc(alias = "ibus_prop_list_update_property")]
    fn update_property(&self, prop: &impl IsA<Property>) -> bool {
        unsafe {
            from_glib(ffi::ibus_prop_list_update_property(self.as_ref().to_glib_none().0, prop.as_ref().to_glib_none().0))
        }
    }
}

impl<O: IsA<PropList>> PropListExt for O {}
